name: Send Quiet Hours Notifications

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call Send Notifications API
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.API_URL }}/api/send-notifications"
        
      - name: Log completion
        run: echo "Notification cron job completed at $(date)"